version: '3.4'
services:
  hello:
    build:
      context: .
    volumes:
      - .:/go/src/hello
    ports:
      - 8080:8080
    depends_on:
      - mongo
    tty: true
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017